#
# Module manifest for module 'ModuleAppLockerImport.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 11-2-2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the Module 'AppLocker Import'.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to classes, functions and variables, that may be in other files.
.EXAMPLE
    Import-ModuleAppLockerImport
.INPUTS
    [System.Windows.Forms.TabControl]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : August 2025
    Last Update     : February 2026
#>
####################################################################################################

function Import-ModuleAppLockerImport {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The Parent TabControl to which this new TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl = $Global:MainTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Submodule properties
        [System.Collections.Hashtable]$SubModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = 'APPLOCKER Import'
            Version             = '5.7.1'
            BackGroundColor     = 'RoyalBlue'
        }

        ####################################################################################################
    }
    
    process {
        try {
            # Create the Module TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @SubModuleProperties

            # Import the Features
            Import-FeatureAppLockerImport -ParentTabPage $ParentTabPage
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


