#
# Module 'ModuleAppLocker.psm1'
# Generated by  : Imraan Iotana
# Creation Date : February 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the Module 'AppLocker'.
.DESCRIPTION
    Creates the AppLocker module TabPage under the provided ParentTabControl and loads its submodules.
.EXAMPLE
    Import-ModuleAppLocker
.INPUTS
    [System.Windows.Forms.TabControl]
.OUTPUTS
    This function returns no stream output.
.NOTES
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : August 2025
    Last Update     : February 2026
#>
####################################################################################################

function Import-ModuleAppLocker {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The Parent TabControl to which this new TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl = $Global:MainTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Module properties
        [System.Collections.Hashtable]$ModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = 'APPLOCKER'
            Version             = '5.7.2'
        }

        ####################################################################################################
    }
    
    process {
        try {
            # Create the Module TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @ModuleProperties

            # Create a SubTabControl
            [System.Windows.Forms.TabControl]$ParentSubTabControl = Invoke-SubTabControl -ParentTabPage $ParentTabPage

            # Import the SubModules
            Import-SubModuleAppLockerImport     -ParentTabControl $ParentSubTabControl
            Import-SubModuleAppLockerCreation   -ParentTabControl $ParentSubTabControl
            Import-SubModuleAppLockerSettings   -ParentTabControl $ParentSubTabControl
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


