#
# Module manifest for module 'ModuleAppLockerImport.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 11-2-2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the SubModule 'AppLocker Import'.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-SubModuleAppLockerImport
.INPUTS
    [System.Windows.Forms.TabControl]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : August 2025
    Last Update     : February 2026
#>
####################################################################################################

function Import-SubModuleAppLockerImport {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabControl to which this new TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Submodule properties
        [System.Collections.Hashtable]$SubModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = 'AppLocker Import'
            Version             = '5.7.1'
            BackGroundColor     = 'RoyalBlue'
        }

        ####################################################################################################
    }
    
    process {
        try {
            # Create the SubModule TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @SubModuleProperties

            # Import the Features
            Import-FeatureAppLockerImport -ParentTabPage $ParentTabPage
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


