#
# Module manifest for module 'ModuleAppLockerSubModuleCreation.psm1'
# Generated by  : Imraan Iotana
# Creation Date : February 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the SubModule 'AppLocker Creation'.
.DESCRIPTION
    Creates the AppLocker Creation submodule TabPage under the provided ParentTabControl and loads its feature UI.
.EXAMPLE
    Import-SubModuleAppLockerCreation
.INPUTS
    [System.Windows.Forms.TabControl]
.OUTPUTS
    This function returns no stream output.
.NOTES
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : September 2025
    Last Update     : February 2026
#>
####################################################################################################

function Import-SubModuleAppLockerCreation {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabControl to which this new TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # SubModule properties
        [System.Collections.Hashtable]$SubModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = 'AppLocker CREATION'
            Version             = '5.7.2'
            BackGroundColor     = 'RoyalBlue'
        }

        ####################################################################################################
    }
    
    process {
        try {
            # Create the SubModule TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @SubModuleProperties

            # Import the Features
            Import-FeatureAppLockerCreation -ParentTabPage $ParentTabPage
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This Feature creates AppLocker XML files and saves them in the Appliction Folder on the DSL.
.DESCRIPTION
    Builds the AppLocker Creation feature UI under the provided ParentTabPage and wires actions for generating policy files.
.EXAMPLE
    Import-FeatureAppLockerCreation
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
    Version         : 5.7.2
    Author          : Imraan Iotana
    Creation Date   : June 2025
    Last Updated    : February 2026
#>
####################################################################################################

function Import-FeatureAppLockerCreation {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]$ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [PSCustomObject]$GroupBox   = @{
            Title                   = [System.String]'Create AppLocker Policy'
            Color                   = [System.String]'LightCyan'
            NumberOfRows            = [System.Int32]8
        }

        # Set the Button Properties Array
        [System.Object[][]]$MAppLock_SCreate_FolderToScan_TextBox_Buttons   = @( (1,'Browse') , (3,'Copy') , (4,'Paste') , (5,'Open') )
        [System.Object[][]]$MAppLock_SCreate_ADGroupSID_TextBox_Buttons     = @( (4,'Copy') , (5,'Paste') )

        ####################################################################################################
        ### TEXTBOX PROPERTIES ###

        # Set the MAppLock_SCreate_ApplicationID_ComboBox properties
        [System.Collections.Hashtable]$MAppLock_SCreate_ApplicationID_ComboBox_Properties = @{
            RowNumber               = 1
            Label                   = 'Select Application ID:'
            ToolTip                 = 'Select the Application ID for the AppLocker policy.'
            PropertyName            = 'MAppLock_SCreate_ApplicationID_ComboBox'
        }

        # Set the MAppLock_SCreate_FolderToScan_TextBox properties
        [System.Collections.Hashtable]$MAppLock_SCreate_FolderToScan_TextBox_Properties = @{
            RowNumber               = 3
            Label                   = 'Select Folder to scan:'
            ToolTip                 = 'Select the folder that contains the files to be scanned for AppLocker rules creation.'
            PropertyName            = 'MAppLock_SCreate_FolderToScan_TextBox'
            ButtonPropertiesArray   = $MAppLock_SCreate_FolderToScan_TextBox_Buttons
        }

        # Set the MAppLock_SCreate_ADGroupSID_TextBox properties
        [System.Collections.Hashtable]$MAppLock_SCreate_ADGroupSID_TextBox_Properties = @{
            RowNumber               = 6
            Label                   = 'AD Group SID:'
            ToolTip                 = 'Enter the AD Group SID for the AppLocker policy.'
            PropertyName            = 'MAppLock_SCreate_ADGroupSID_TextBox'
            ButtonPropertiesArray   = $MAppLock_SCreate_ADGroupSID_TextBox_Buttons
        }

        ####################################################################################################
        ### BUTTON PROPERTIES ###

        [System.Collections.Hashtable[]]$ALCApplicationIDComboBoxButtons = @(
            @{
                ColumnNumber    = 5
                Text            = 'Open'
                DefaultIcon     = 'Folder'
                SizeType        = 'Small'
                ToolTip         = 'Open the AppLocker folder'
                Function        = { Open-Folder -Path (Get-Path -ApplicationID $Global:ALCApplicationIDComboBox.Text -SubFolder AppLockerFolder) }
            }
        )

        [System.Collections.Hashtable[]]$ActionButtons = @(
           @{
                ColumnNumber    = 5
                Text            = 'Create AppLocker Policy Files'
                DefaultIcon     = 'Shield'
                SizeType        = 'Large'
                ToolTip         = 'Create AppLocker Policy Files from the selected folder'
                Function        = { Invoke-AppLockerFileCreation -ApplicationID $Global:ALCApplicationIDComboBox.Text -FolderToScan $Script:MAppLock_SCreate_FolderToScan_TextBox.Text -ADGroupSID $Global:ALCADGroupSIDTextBox.Text }
            }
        )

        ####################################################################################################
    } 
    
    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$Global:AppLockerCreationGroupbox = $ParentGroupBox = Invoke-Groupbox -ParentTabPage $ParentTabPage -Title $Groupbox.Title -NumberOfRows $Groupbox.NumberOfRows -Color $Groupbox.Color

        # Create the MAppLock_SCreate_ApplicationID_ComboBox
        [System.Windows.Forms.ComboBox]$Script:MAppLock_SCreate_ApplicationID_ComboBox = Invoke-ComboBox @MAppLock_SCreate_ApplicationID_ComboBox_Properties -ParentGroupBox $ParentGroupBox
        Invoke-ButtonLine -ButtonPropertiesArray $ALCApplicationIDComboBoxButtons -ParentGroupBox $ParentGroupBox -RowNumber 1

        # Create the MAppLock_SCreate_FolderToScan_TextBox
        [System.Windows.Forms.TextBox]$Script:MAppLock_SCreate_FolderToScan_TextBox = Invoke-TextBox @MAppLock_SCreate_FolderToScan_TextBox_Properties -ParentGroupBox $ParentGroupBox

        # Create the MAppLock_SCreate_ADGroupSID_TextBox
        [System.Windows.Forms.TextBox]$Script:MAppLock_SCreate_ADGroupSID_TextBox = Invoke-TextBox @MAppLock_SCreate_ADGroupSID_TextBox_Properties -ParentGroupBox $ParentGroupBox

        # Create the action button
        Invoke-ButtonLine -ButtonPropertiesArray $ActionButtons -ParentGroupBox $ParentGroupBox -RowNumber 9
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


