#
# Module manifest for module 'ModuleAppLockerSubModuleImport.psm1'
# Generated by  : Imraan Iotana
# Creation Date : February 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the SubModule 'AppLocker Import'.
.DESCRIPTION
    Creates the AppLocker Import submodule TabPage under the provided ParentTabControl and loads its feature UI.
.EXAMPLE
    Import-SubModuleAppLockerImport
.INPUTS
    [System.Windows.Forms.TabControl]
.OUTPUTS
    This function returns no stream output.
.NOTES
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : August 2025
    Last Update     : February 2026
#>
####################################################################################################

function Import-SubModuleAppLockerImport {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The Parent TabControl to which this new TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl = $Global:MainTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # SubModule properties
        [System.Collections.Hashtable]$SubModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = 'AppLocker IMPORT'
            Version             = '5.7.2'
            BackGroundColor     = 'RoyalBlue'
        }

        ####################################################################################################
    }
    
    process {
        try {
            # Create the SubModule TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @SubModuleProperties

            # Import the Features
            Import-FeatureAppLockerImport -ParentTabPage $ParentTabPage
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This Feature imports the AppLocker XML files into the AppLocker Policy.
.DESCRIPTION
    Builds the AppLocker Import feature UI under the provided ParentTabPage and wires actions for policy import.
.EXAMPLE
    Import-FeatureAppLockerImport
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
    Version         : 5.7.2
    Author          : Imraan Iotana
    Creation Date   : August 2025
    Last Updated    : February 2026
#>
####################################################################################################

function Import-FeatureAppLockerImport {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]$ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = 'AppLocker Policy Import'
            Color           = 'LightCyan'
            NumberOfRows    = 7
        }

        # ComboBox Handlers
        [System.String[]]$DSLApplicationFolders = Get-DSLApplicationFolder -All -Basenames

        # LDAP Handlers
        [System.Collections.Hashtable]$Script:MApplock_LDAPEnvironmentHashtable = @{
            DEVELOPMENT = (Get-ApplicationSetting -Name 'AppLockerLDAPDEV')
            TEST        = (Get-ApplicationSetting -Name 'AppLockerLDAPTEST')
            ACCEPTANCE  = (Get-ApplicationSetting -Name 'AppLockerLDAPACC')
            PRODUCTION  = (Get-ApplicationSetting -Name 'AppLockerLDAPPROD')
        }
        [System.String[]]$MApplock_EnvironmentOrder = @('DEVELOPMENT','TEST','ACCEPTANCE','PRODUCTION')

        ####################################################################################################
        ### COMBOBOX PROPERTIES ###

        # Set the parameters for the MApplock_FApplock_ApplicationComboBox
        [System.Collections.Hashtable]$MApplock_FApplock_ApplicationComboBoxParameters = @{
            RowNumber       = 1
            SizeType        = 'Medium'
            Type            = 'Output'
            Label           = 'Select Application ID:'
            ContentArray    = $DSLApplicationFolders
            PropertyName    = 'MApplock_FApplock_ApplicationComboBox'
            ToolTip         = 'Select the Application for which you want to import the AppLocker Policy'
        }

         # Set the parameters for the MApplock_SImp_FImp_SelectedEnvironmentComboBox
        [System.Collections.Hashtable]$MApplock_SImp_FImp_SelectedEnvironmentComboBoxParameters = @{
            RowNumber       = 2
            SizeType        = 'Medium'
            Type            = 'Output'
            Label           = 'Select Environment:'
            ContentArray    = $MApplock_EnvironmentOrder
            PropertyName    = 'MApplock_SImp_FImp_SelectedEnvironmentComboBox'
            ToolTip         = 'Select the Environment into which you want to import the AppLocker Policy'
        }

        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the SMALL buttons for the MApplock_FApplock_ApplicationComboBox
        [System.Collections.Hashtable[]]$MApplock_FApplock_ApplicationComboBoxButtons = @(
            @{
                ColumnNumber    = 5
                Text            = 'Open AppLocker Folder'
                DefaultIcon     = 'Folder'
                SizeType        = 'Small'
                ToolTip         = 'Open the AppLocker folder of the selected Application'
                Function        = { Open-Folder -Path (Get-Path -ApplicationID $Script:MApplock_FApplock_ApplicationComboBox.Text -SubFolder AppLockerFolder) }
            }
            @{
                ColumnNumber    = 6
                Text            = 'Show Application Log'
                DefaultIcon     = 'Logfile'
                SizeType        = 'Small'
                ToolTip         = 'Open the logfile of the selected Application'
                Function        = { Show-ApplicationLogFile -ApplicationID $Script:MApplock_FApplock_ApplicationComboBox.Text }
            }
            @{
                ColumnNumber    = 7
                Text            = 'Copy'
                SizeType        = 'Small'
                ToolTip         = 'Copy the the selected Application ID to the clipboard'
                Function        = { Invoke-ClipBoard -CopyFromBox $Script:MApplock_FApplock_ApplicationComboBox }
            }
        )

        # Set the SMALL buttons for the MApplock_SImp_FImp_SelectedEnvironmentComboBox
        [System.Collections.Hashtable[]]$MApplock_SImp_FImp_SelectedEnvironmentComboBoxButtons = @(
            @{
                ColumnNumber    = 5
                Text            = 'Export Policy'
                DefaultIcon     = 'Table_Export'
                SizeType        = 'Small'
                ToolTip         = 'Export the AppLocker Policy'
                Function        = { Export-AppLockerPolicy -AppLockerLDAP $Script:MApplock_LDAPEnvironmentHashtable }
            }
        )

        # Set the LARGE buttons for the Actions
        [System.Collections.Hashtable[]]$ActionButtons = @(
           @{
                ColumnNumber    = 1
                Text            = 'Check AppLocker Policy'
                TextColor       = 'LightCyan'
                DefaultIcon     = 'Shield'
                SizeType        = 'Large'
                ToolTip         = 'Check the AppLocker Policy'
                Function        = { Test-AppLockerPolicy -ApplicationID $Script:MApplock_FApplock_ApplicationComboBox.Text -AppLockerLDAP $Script:MApplock_SelectedAppLockerLDAP }
            }
           @{
                ColumnNumber    = 3
                Text            = 'Import AppLocker Policy'
                TextColor       = 'LightGreen'
                DefaultIcon     = 'Shield_Add'
                SizeType        = 'Large'
                ToolTip         = 'Import the AppLocker Policy'
                Function        = { Add-AppLockerPolicy -ApplicationID $Script:MApplock_FApplock_ApplicationComboBox.Text -AppLockerLDAP $Script:MApplock_SelectedAppLockerLDAP }
            }
           @{
                ColumnNumber    = 5
                Text            = 'Remove AppLocker Policy'
                TextColor       = 'Orange'
                DefaultIcon     = 'Shield_Delete'
                SizeType        = 'Large'
                ToolTip         = 'Remove the AppLocker Policy'
                Function        = { Remove-AppLockerPolicy -ApplicationID $Script:MApplock_FApplock_ApplicationComboBox.Text -AppLockerLDAP $Script:MApplock_SelectedAppLockerLDAP }
            }
        )

        # Set the MEDIUM buttons for the Extra Actions
        [System.Collections.Hashtable[]]$ExtraActionButtons = @(
            @{
                RowNumber       = 7
                Text            = 'Details in Host'
                DefaultIcon     = 'Shield'
                ToolTip         = 'Check the AppLocker Policy and show the result in the Host'
                Function        = { Test-AppLockerPolicy -ApplicationID $Script:MApplock_FApplock_ApplicationComboBox.Text -AppLockerLDAP $Script:MApplock_SelectedAppLockerLDAP -OutHost }
            }
            @{
                RowNumber       = 8
                Text            = 'Details in Grid'
                DefaultIcon     = 'Shield'
                ToolTip         = 'Check the AppLocker Policy and show the result in a Gridview'
                Function        = { Test-AppLockerPolicy -ApplicationID $Script:MApplock_FApplock_ApplicationComboBox.Text -AppLockerLDAP $Script:MApplock_SelectedAppLockerLDAP -OutGridView }
            }
        )

        ####################################################################################################
    } 
    
    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$Global:MApplock_FApplock_GroupBox = $ParentGroupBox = Invoke-Groupbox @GroupBoxProperties

        # Create the MApplock_FApplock_ApplicationComboBox
        [System.Windows.Forms.ComboBox]$Script:MApplock_FApplock_ApplicationComboBox = Invoke-ComboBox @MApplock_FApplock_ApplicationComboBoxParameters -ParentGroupBox $ParentGroupBox
        
        # Create the MApplock_SImp_FImp_SelectedEnvironmentComboBox
        [System.Windows.Forms.ComboBox]$Script:MApplock_SImp_FImp_SelectedEnvironmentComboBox = Invoke-ComboBox @MApplock_SImp_FImp_SelectedEnvironmentComboBoxParameters -ParentGroupBox $ParentGroupBox
        # Set the initial selection and the initial AppLocker LDAP value
        [System.String]$InitialSelectedEnvironment              = $Script:MApplock_SImp_FImp_SelectedEnvironmentComboBox.Text
        [System.String]$Script:MApplock_SelectedAppLockerLDAP   = $Script:MApplock_LDAPEnvironmentHashtable.$InitialSelectedEnvironment
        # Add the event handler for the MApplock_SImp_FImp_SelectedEnvironmentComboBox to update the selected AppLocker LDAP value, when the selection changes
        $Script:MApplock_SImp_FImp_SelectedEnvironmentComboBox.Add_SelectedIndexChanged([System.EventHandler]{
            [System.String]$SelectedEnvironment                     = $Script:MApplock_SImp_FImp_SelectedEnvironmentComboBox.Text
            [System.String]$Script:MApplock_SelectedAppLockerLDAP   = $Script:MApplock_LDAPEnvironmentHashtable.$SelectedEnvironment
            Write-Line ("The AppLocker LDAP Environment has changed to: $SelectedEnvironment") -Type Busy
            Write-Line ("($Script:MApplock_SelectedAppLockerLDAP)")
        })

        # Create the buttons
        Invoke-ButtonLine -ButtonPropertiesArray $MApplock_FApplock_ApplicationComboBoxButtons -ParentGroupBox $ParentGroupBox -RowNumber 1
        Invoke-ButtonLine -ButtonPropertiesArray $MApplock_SImp_FImp_SelectedEnvironmentComboBoxButtons -ParentGroupBox $ParentGroupBox -RowNumber 2
        Invoke-ButtonLine -ButtonPropertiesArray $ActionButtons -ParentGroupBox $ParentGroupBox -RowNumber 4
        Invoke-ButtonLine -ButtonPropertiesArray $ExtraActionButtons -ParentGroupBox $ParentGroupBox -ColumnNumber 1
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################

