#
# Module manifest for module 'SubModuleMaintenanceFeatureUpdates.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 22-1-2026
# Last Update   : January 2026
#

####################################################################################################
<#
.SYNOPSIS
    This feature manages the updates of the Packaging Assistant.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-FeatureUpdates
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.0
    Author          : Imraan Iotana
    Creation Date   : January 2026
    Last Update     : January 2026
#>
####################################################################################################

function Import-FeatureUpdates {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]
        $ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [PSCustomObject]$GroupBox = @{
            Title           = [System.String]'Updates'
            Color           = [System.String]'Blue'
            NumberOfRows    = [System.Int32]4
            GroupBoxAbove   = $Global:FAMMaintenanceGroupBox
        }


        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the Buttons
        [System.Collections.Hashtable[]]$ButtonPropertiesArray = @(
            @{
                ColumnNumber    = 1
                Text            = 'Copy'
                Image           = 'page_copy.png'
                SizeType        = 'Medium'
                ToolTip         = 'Copy the content of the textbox to your clipboard.'
                Function        = { Invoke-ClipBoard -CopyFromBox $Global:SMFUURLTextBox }
            }
            @{
                ColumnNumber    = 2
                Text            = 'Paste'
                Image           = 'page_paste.png'
                SizeType        = 'Medium'
                ToolTip         = 'Paste the content of your clipboard to the textbox'
                Function        = { Invoke-ClipBoard -PasteToBox $Global:SMFUURLTextBox }
            }
            @{
                ColumnNumber    = 3
                Text            = 'Clear'
                Image           = 'textfield_delete.png'
                SizeType        = 'Medium'
                ToolTip         = 'Clear the textbox.'
                Function        = { Invoke-ClipBoard -ClearBox $Global:SMFUURLTextBox }
            }
            @{
                ColumnNumber    = 5
                Text            = 'Default'
                Image           = 'arrow_undo.png'
                SizeType        = 'Medium'
                ToolTip         = 'Reset the textbox to the default value.'
                Function        = { if (Get-UserConfirmation -Title 'Reset to default' -Body ("This will reset this field to the default value:`n`n({0})`n`nAre you sure?" -f $Global:SMFUURLTextBox.DefaultValue)) { $Global:SMFUURLTextBox.Text = $Global:SMFUURLTextBox.DefaultValue } }
            }
        )

        ####################################################################################################
    }

    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$Global:SMFeatureUpdatesGroupBox = $ParentGroupBox = Invoke-Groupbox -ParentTabPage $ParentTabPage -Title $GroupBox.Title -NumberOfRows $GroupBox.NumberOfRows -Color $GroupBox.Color -GroupBoxAbove $GroupBox.GroupBoxAbove
        # Create the ComboBox
        [System.Windows.Forms.TextBox]$Global:SMFUURLTextBox = Invoke-TextBox -ParentGroupBox $ParentGroupBox -RowNumber 1 -SizeType Large -Type Input -Label 'URL to zip file:' -PropertyName 'SMFUURLTextBox'
        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $ButtonPropertiesArray -ParentGroupBox $ParentGroupBox -RowNumber 2 -AssetFolder $PSScriptRoot
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################

