#
# Module manifest for module 'SubModuleMaintenanceFeatureUpdates.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 22-1-2026
# Last Update   : January 2026
#

####################################################################################################
<#
.SYNOPSIS
    This feature manages the updates of the Packaging Assistant.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-FeatureUpdates -ParentTabPage $Global:ParentTabPage
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.0
    Author          : Imraan Iotana
    Creation Date   : January 2026
    Last Update     : January 2026
#>
####################################################################################################

function Import-FeatureUpdates {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]
        $ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [PSCustomObject]$GroupBox = @{
            Title           = [System.String]'Updates'
            Color           = [System.String]'Blue'
            NumberOfRows    = [System.Int32]5
            GroupBoxAbove   = $Global:FAMMaintenanceGroupBox
        }

        # Handlers
        [System.String]$SMFUURLTextBoxDefaultValue = $Global:ApplicationObject.Settings.ZipFileOnGithub

        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the URL Buttons
        [System.Collections.Hashtable[]]$URLButtonProperties = @(
            @{
                ColumnNumber    = 1
                Text            = 'Download'
                Image           = 'inbox_upload.png'
                SizeType        = 'Medium'
                ToolTip         = 'Download the file.'
                Function        = { Get-ApplicationUpdate -URL $Global:SMFUURLTextBox.Text }
            }
            @{
                ColumnNumber    = 3
                Text            = 'Copy'
                Image           = 'page_copy.png'
                SizeType        = 'Medium'
                ToolTip         = 'Copy the content of the textbox to your clipboard.'
                Function        = { Invoke-ClipBoard -CopyFromBox $Global:SMFUURLTextBox }
            }
            @{
                ColumnNumber    = 4
                Text            = 'Paste'
                Image           = 'page_paste.png'
                SizeType        = 'Medium'
                ToolTip         = 'Paste the content of your clipboard to the textbox'
                Function        = { Invoke-ClipBoard -PasteToBox $Global:SMFUURLTextBox }
            }
            @{
                ColumnNumber    = 5
                Text            = 'Default'
                Image           = 'arrow_undo.png'
                SizeType        = 'Medium'
                ToolTip         = 'Reset the textbox to the default value.'
                Function        = { if (Get-UserConfirmation -Title 'Reset to default' -Body ("This will reset this field to the default value:`n`n({0})`n`nAre you sure?" -f $Global:SMFUURLTextBox.DefaultValue)) { $Global:SMFUURLTextBox.Text = $Global:SMFUURLTextBox.DefaultValue } }
            }
        )

        # Set the Installation Folder Buttons
        [System.Collections.Hashtable[]]$InstallationFolderButtonProperties = @(
            @{
                ColumnNumber    = 1
                Text            = 'Browse'
                Image           = 'folders_explorer.png'
                SizeType        = 'Medium'
                ToolTip         = 'Browse to the installation folder.'
                Function        = { [System.String]$FolderName = Select-Item -Folder ; if ($FolderName) { $Global:SMFUInstallationFolderTextBox.Text = $FolderName } }
            }
            @{
                ColumnNumber    = 3
                Text            = 'Copy'
                Image           = 'page_copy.png'
                SizeType        = 'Medium'
                ToolTip         = 'Copy the content of the textbox to your clipboard.'
                Function        = { Invoke-ClipBoard -CopyFromBox $Global:SMFUInstallationFolderTextBox }
            }
            @{
                ColumnNumber    = 4
                Text            = 'Paste'
                Image           = 'page_paste.png'
                SizeType        = 'Medium'
                ToolTip         = 'Paste the content of your clipboard to the textbox'
                Function        = { Invoke-ClipBoard -PasteToBox $Global:SMFUInstallationFolderTextBox }
            }
            @{
                ColumnNumber    = 5
                Text            = 'Clear'
                Image           = 'textfield_delete.png'
                SizeType        = 'Medium'
                ToolTip         = 'Clear the textbox.'
                Function        = { Invoke-ClipBoard -ClearBox $Global:SMFUInstallationFolderTextBox }
            }
        )

        ####################################################################################################
    }

    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$Global:SMFeatureUpdatesGroupBox = $ParentGroupBox = Invoke-Groupbox -ParentTabPage $ParentTabPage -Title $GroupBox.Title -NumberOfRows $GroupBox.NumberOfRows -Color $GroupBox.Color -GroupBoxAbove $GroupBox.GroupBoxAbove

        # Create the URL TextBox
        [System.Windows.Forms.TextBox]$Global:SMFUURLTextBox = Invoke-TextBox -ParentGroupBox $ParentGroupBox -RowNumber 1 -SizeType Large -Type Input -Label 'URL to zip file:' -PropertyName 'SMFUURLTextBox'
        $Global:SMFUURLTextBox | Add-Member -NotePropertyName DefaultValue -NotePropertyValue $SMFUURLTextBoxDefaultValue
        $Global:SMFUURLTextBox | ForEach-Object {
            if (Test-Object -IsEmpty ($_.Text)) {
                Write-Line ('The Update URL field is empty. It will be filled with the default value: ({0})' -f $_.DefaultValue)
                $_.Text = $_.DefaultValue
            }
        }
        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $URLButtonProperties -ParentGroupBox $ParentGroupBox -RowNumber 2 -AssetFolder $PSScriptRoot

        # Create the Installation Folder TextBox
        [System.Windows.Forms.TextBox]$Global:SMFUInstallationFolderTextBox = Invoke-TextBox -ParentGroupBox $ParentGroupBox -RowNumber 4 -SizeType Large -Type Input -Label 'Installation Folder:' -PropertyName 'SMFUInstallationFolderTextBox'
        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $InstallationFolderButtonProperties -ParentGroupBox $ParentGroupBox -RowNumber 5 -AssetFolder $PSScriptRoot
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function downloads the update file from the URL.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Get-ApplicationUpdate
.INPUTS
    -
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.0
    Author          : Imraan Iotana
    Creation Date   : January 2026
    Last Update     : January 2026
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Get-ApplicationUpdate {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [System.String]$URL
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$ZipFileToDownload       = $URL

        # Download Handlers
        [System.String]$OutputFolder            = Get-Path -OutputFolder
        [System.String]$OutputFileName          = "PAUpdate.zip"
        [System.String]$OutputFilePath          = Join-Path -Path $OutputFolder -ChildPath $OutputFileName

        # Extraction Handlers
        [System.String]$CurrentVersion          = $Global:ApplicationObject.Version
        [System.String]$ExtractFolder           = Join-Path -Path $OutputFolder -ChildPath ("Update for PA $CurrentVersion")

        # Other Handlers
        [System.String]$InstallationFolder      = $Global:SMFUInstallationFolderTextBox.Text
        [System.String]$UpdateScriptFileName    = "Install-PAUpdate.ps1"
        [System.String]$UpdateScriptFilePath    = Join-Path -Path $OutputFolder -ChildPath $UpdateScriptFileName

        ####################################################################################################

    }
    
    process {
        # VALIDATION
        # If the URL is empty, return
        if ([System.String]::IsNullOrEmpty($ZipFileToDownload)) { Write-Line "The URL is empty. No action has been taken." ; Return }

        # PREPARATION
        # If the zip file already exists, remove it
        if (Test-Path -Path $OutputFilePath) { Write-Line "Removing the previous update file... ($OutputFilePath)" ; Remove-Item -Path $OutputFilePath -Force }
        # If the extract folder already exists, remove it
        if (Test-Path -Path $ExtractFolder) { Write-Line "Removing the previous extracted folder... ($ExtractFolder)" ; Remove-Item -Path $ExtractFolder -Recurse -Force }
        # If the update script already exists, remove it
        if (Test-Path -Path $UpdateScriptFilePath) { Write-Line "Removing the previous update script... ($UpdateScriptFilePath)" ; Remove-Item -Path $UpdateScriptFilePath -Force }


        # EXECUTION
        try {
            # Download the update file
            Write-Line "Downloading update... ($ZipFileToDownload)" -Type Busy
            Invoke-WebRequest $ZipFileToDownload -OutFile $OutputFilePath

            <# Extract the update file
            Write-Line "Extracting the update file to folder... ($OutputFolder)" -Type Busy
            Expand-Archive -Path $OutputFilePath -DestinationPath $ExtractFolder -Force

            # Switch on the number of folders inside the extract folder
            [System.IO.DirectoryInfo[]]$FolderObjects = Get-ChildItem -Path $ExtractFolder -Directory
            switch ($FolderObjects.Count) {
                1 {
                    # Change the value of the extract folder
                    [System.String]$FolderToCopyFrom = $FolderObjects[0].FullName
                }
                default {
                    # Do nothing
                }
            }#>

            # Remove the update file after extraction
            #Write-Line "Removing the update file... ($OutputFilePath)" -Type Busy
            #Remove-Item -Path $OutputFilePath -Force

            # Set the update script content
            [System.String]$UpdateScriptContent = @"
            Write-Host "Starting the update process..." -ForegroundColor Cyan

            # Extract the update file
            Write-Host "Extracting the update file to folder... ($OutputFolder)" -ForegroundColor Yellow
            Expand-Archive -Path $OutputFilePath -DestinationPath $ExtractFolder -Force

            # Switch on the number of folders inside the extract folder
            [System.IO.DirectoryInfo[]]`$FolderObjects = Get-ChildItem -Path $ExtractFolder -Directory
            switch (`$FolderObjects.Count) {
                1 {
                    # Change the value of the extract folder
                    [System.String]$`FolderToCopyFrom = $`FolderObjects[0].FullName
                }
                default {
                    # Do nothing
                }
            }
        
            Write-Host "Removing the update file... ($OutputFilePath)" -ForegroundColor Yellow
            Remove-Item -Path $OutputFilePath -Force
            Write-Host "Removing the old files from the installation folder... ($InstallationFolder)" -ForegroundColor Yellow
            Remove-Item -Path "$InstallationFolder\*" -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "Copying the new files to the installation folder... ($InstallationFolder)" -ForegroundColor Yellow
            Copy-Item -Path "$FolderToCopyFrom\*" -Destination "$InstallationFolder" -Recurse -Force
            Write-Host "Removing the Extract folder... ($ExtractFolder)" -ForegroundColor Yellow
            Remove-Item -Path "$ExtractFolder" -Recurse -Force -ErrorAction SilentlyContinue
            Write-Host "Update process completed successfully!" -ForegroundColor Green
            Start-Sleep -Seconds 2
"@
            # Create the update script file
            Write-Line "Creating the update script..." -Type Busy
            Set-Content -Path $UpdateScriptFilePath -Value $UpdateScriptContent -Force -Encoding UTF8

            # Write the message
            Write-Line "The update has been downloaded." -Type Success
            Write-Line "Please close this application, and run the script: ($UpdateScriptFilePath)." -Type Success
            Write-Line "Then restart this application." -Type Success

            # Open the output folder
            Open-Folder -Path $OutputFolder
        }
        catch [System.Net.WebException] {
            # Write the error message
            Write-Line "The update file could not be reached. Please check your spelling (or your internet connection) and try again." -Type Fail
        }
        catch {
            Write-FullError
        }
    }
    
    end {
    }
}

### END OF SCRIPT
####################################################################################################

