#
# Module manifest for module 'SubModuleMaintenanceFeatures.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 21-1-2026
# Last Update   : January 2026
#

####################################################################################################
<#
.SYNOPSIS
    This feature performs maintenance on the Packaging Assistant.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-FeatureMaintenance
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.0
    Author          : Imraan Iotana
    Creation Date   : September 2025
    Last Update     : January 2026
#>
####################################################################################################

function Import-FeatureMaintenance {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]
        $ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [PSCustomObject]$GroupBox = @{
            Title           = [System.String]'Maintenance'
            Color           = [System.String]'Blue'
            NumberOfRows    = [System.Int32]4
        }

        # Set the Action Hashtable
        [System.Collections.Hashtable]$Script:ActionHashtable = @{
            UpdatePA        = 'GENERAL: Update the Packaging Assistant'
            ShowFormsColors = 'GENERAL: Write Windows Forms Colors to Host'
            UpdateScript    = 'APPLICATION INTAKE: Update the DeploymentScript'
            TestModule      = 'TEST: Test the new module'
        }


        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the ScriptBlock for the Execute Action button
        [System.Management.Automation.ScriptBlock]$Script:ExecuteActionScriptBlock = {
            # Get the selected key from the hashtable
            [System.String]$SelectedKey = $Script:ActionHashtable.Keys | Where-Object { $Script:ActionHashtable.$_ -eq $Global:FAMActionComboBox.Text }
            # Perform the action based on the selected key
            switch ($SelectedKey) {
                'UpdateScript'      { Update-InternalDeploymentScript }
                'ShowFormsColors'   {
                    Write-Line "Executing Maintenance: [$($Global:FAMActionComboBox.Text)]"
                    Write-WindowsFormsColors
                }
                'TestModule'        { Test-NewModule }
                Default             { Write-Line "This Action has not been implemented yet. No action has been taken." }
            }
        }

        # Set the Buttons
        [System.Collections.Hashtable[]]$ButtonPropertiesArray = @(
           @{
                ColumnNumber    = 1
                Text            = 'Execute the Action'
                Image           = 'cog_go.png'
                SizeType        = 'Large'
                ToolTip         = 'Execute the selected Maintenance Action'
                Function        = { & $Script:ExecuteActionScriptBlock }
            }
        )

        ####################################################################################################
    }

    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$Global:FAMMaintenanceGroupBox = $ParentGroupBox = Invoke-Groupbox -ParentTabPage $ParentTabPage -Title $GroupBox.Title -NumberOfRows $GroupBox.NumberOfRows -Color $GroupBox.Color
        # Create the ComboBox
        [System.Windows.Forms.ComboBox]$Global:FAMActionComboBox = Invoke-ComboBox -ParentGroupBox $ParentGroupBox -RowNumber 1 -SizeType Medium -Type Output -Label 'Select Action:' -ContentArray $Script:ActionHashtable.Values -PropertyName 'FAMActionComboBox'
        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $ButtonPropertiesArray -ParentGroupBox $ParentGroupBox -RowNumber 2 -AssetFolder $PSScriptRoot
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function writes the Windows Forms Colors to the host.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Write-WindowsFormsColors
.INPUTS
    -
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.0
    Author          : Imraan Iotana
    Creation Date   : September 2025
    Last Update     : January 2026
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Write-WindowsFormsColors {
    [CmdletBinding()]
    param (
    )

    begin {
    }
    
    process {
        # EXECUTION
        [PSCustomObject[]]$Colors = [System.Drawing.Color] | Get-Member -Static | Where-Object { $_.MemberType -eq 'Property' } | Select-Object Name | Sort-Object Name
        $Colors | Out-Host
    }
    
    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
function Test-NewModule {
    Write-Host "TESTING: Test-NewModule called" -ForegroundColor Green
}
####################################################################################################
