#
# Module manifest for module 'SubModuleMaintenanceFeatureUpdates.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 22-1-2026
# Last Update   : January 2026
#

####################################################################################################
<#
.SYNOPSIS
    This feature manages the updates of the Packaging Assistant.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-FeatureUpdates
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.0
    Author          : Imraan Iotana
    Creation Date   : January 2026
    Last Update     : January 2026
#>
####################################################################################################

function Import-FeatureUpdates {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]
        $ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [PSCustomObject]$GroupBox = @{
            Title           = [System.String]'Updates'
            Color           = [System.String]'SteelBlue'
            NumberOfRows    = [System.Int32]4
            GroupBoxAbove   = $Global:FAMMaintenanceGroupBox
        }

        # Set the Action Hashtable
        [System.Collections.Hashtable]$Script:ActionHashtable = @{
            UpdatePA        = 'GENERAL: Update the Packaging Assistant'
            ShowFormsColors = 'GENERAL: Write Windows Forms Colors to Host'
            UpdateScript    = 'APPLICATION INTAKE: Update the DeploymentScript'
            TestModule      = 'TEST: Test the new module'
        }


        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the ScriptBlock for the Execute Action button
        [System.Management.Automation.ScriptBlock]$Script:ExecuteActionScriptBlock = {
            # Get the selected key from the hashtable
            [System.String]$SelectedKey = $Script:ActionHashtable.Keys | Where-Object { $Script:ActionHashtable.$_ -eq $Global:FAMActionComboBox.Text }
            # Perform the action based on the selected key
            switch ($SelectedKey) {
                'UpdateScript'      { Update-InternalDeploymentScript }
                'ShowFormsColors'   {
                    Write-Line "Executing Maintenance: [$($Global:FAMActionComboBox.Text)]"
                    Write-WindowsFormsColors
                }
                'TestModule'        { Test-NewModule }
                Default             { Write-Line "This Action has not been implemented yet. No action has been taken." }
            }
        }

        # Set the Buttons
        [System.Collections.Hashtable[]]$ButtonPropertiesArray = @(
           @{
                ColumnNumber    = 1
                Text            = 'Execute the Action'
                Image           = 'cog_go.png'
                SizeType        = 'Large'
                ToolTip         = 'Execute the selected Maintenance Action'
                Function        = { & $Script:ExecuteActionScriptBlock }
            }
        )

        ####################################################################################################
    }

    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$Global:SMFeatureUpdatesGroupBox = $ParentGroupBox = Invoke-Groupbox -ParentTabPage $ParentTabPage -Title $GroupBox.Title -NumberOfRows $GroupBox.NumberOfRows -Color $GroupBox.Color -GroupBoxAbove $GroupBox.GroupBoxAbove
        # Create the ComboBox
        [System.Windows.Forms.ComboBox]$Global:SMFeatureUpdatesComboBox = Invoke-ComboBox -ParentGroupBox $ParentGroupBox -RowNumber 1 -SizeType Medium -Type Output -Label 'Select Action:' -ContentArray $Script:ActionHashtable.Values -PropertyName 'SMFeatureUpdatesComboBox'
        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $ButtonPropertiesArray -ParentGroupBox $ParentGroupBox -RowNumber 2 -AssetFolder $PSScriptRoot
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################

