#
# Module 'ModuleMainFunctionsWrite.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 29-1-2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function writes a line to the host in several colors.
.DESCRIPTION
    This function is part of the Iotana Base Module. It is self-contained and does not refer to functions or variables, that are in other files.
.EXAMPLE
    Write-Line "Hello World!"
.EXAMPLE
    Write-Line "Hello World!" -Type Busy
.EXAMPLE
    Write-Line -Type NoAction
.INPUTS
    [System.String]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1.249
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : February 2026
#>
####################################################################################################

function Write-Line {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,Position=0,HelpMessage='The message that will be written to the host.')]
        [AllowNull()]
        [AllowEmptyString()]
        [System.String]$Message,

        [Parameter(Mandatory=$false,Position=1,HelpMessage='Type for deciding the colors and prefixes.')]
        [ValidateSet('Busy','Fail','NoAction','Normal','Info','Special','Success','EmptyStringNoAction')]
        [System.String]$Type
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$InputMessage    = $Message
        [System.String]$InputType       = $Type

        ####################################################################################################
    }
    
    process {
        # MESSAGE PREPARATION
        # Set the FullMessage
        [System.String]$FullMessage = switch ($InputType) {
            'NoAction'              { 'No action has been taken.' }
            'EmptyStringNoAction'   { "The $InputMessage String is empty. No action has been taken." }
            Default                 { $InputMessage }
        }
        
        # COLOR PREPARATION
        # Set the ForegroundColor
        [System.String]$ForegroundColor = switch ($InputType) {
            'Busy'                  { 'Yellow'  }
            'Fail'                  { 'Red'     }
            'Normal'                { 'White'   }
            'Special'               { 'Cyan'    }
            'Success'               { 'Green'   }
            'Info'                  { 'Yellow'  }
            'EmptyStringNoAction'   { 'Red'     }
            Default                 { 'DarkGray' }
        }
        # Set the BackgroundColor
        [System.String]$BackgroundColor = switch ($InputType) {
            Default             { '' }
        }

        # PARAMETER PREPARATION
        # Set the Write-Host parameters
        [System.Collections.Hashtable]$WriteHostParams = @{
            'Object'            = $FullMessage
            'ForegroundColor'   = $ForegroundColor
        }
        # Add the BackgroundColor if specified
        if (-not [System.String]::IsNullOrEmpty($BackgroundColor)) { $WriteHostParams['BackgroundColor'] = $BackgroundColor }

        # EXECUTION
        # Write the message
        Write-Host @WriteHostParams
    }
    
    end {
    }
}

### END OF FUNCTION
####################################################################################################
