#
# Module 'ModuleMainFunctionsWrite.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 29-1-2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function writes a line to the host in several colors.
.DESCRIPTION
    This function is part of the Iotana Base Module. It is self-contained and does not refer to functions or variables, that are in other files.
.EXAMPLE
    Write-Line "Hello World!"
.EXAMPLE
    Write-Line "Hello World!" -Type Busy
.EXAMPLE
    Write-Line -Type NoAction
.INPUTS
    [System.String]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1.009
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : February 2026
#>
####################################################################################################

function Write-Line {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,Position=0,HelpMessage='The message that will be written to the host.')]
        [AllowNull()]
        [AllowEmptyString()]
        [System.String]
        $Message,

        [Parameter(Mandatory=$false,Position=1,HelpMessage='Type for deciding the colors and prefixes.')]
        [ValidateSet('Normal','Busy','NoAction','Success','SuccessNoAction','ValidationSuccess','Fail','ActionFail','ValidationFail','Special','Seperation','DoubleSeperation')]
        [System.String]
        $Type
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$InputMessage    = $Message
        [System.String]$MessageType     = $Type

        # Get the TimeStamp
        [System.DateTime]$UTCTimeStamp  = [DateTime]::UtcNow
        [System.String]$LogDate         = $UTCTimeStamp.ToString('yyyy-MM-dd')
        [System.String]$LogTime         = $UTCTimeStamp.ToString('HH:mm:ss.fff')
        [System.String]$FullTimeStamp   = "$LogDate $LogTime"

        # Get the Calling Function
        [System.String]$CallingFunction = (Get-PSCallStack)[1].Command

        ####################################################################################################


        # Set the FullMessage
        [System.String]$FullMessage = switch ($MessageType) {
            'NoAction'          { 'No action has been taken.' }
            'SuccessNoAction'   { 'No action has been taken.' }
            'Seperation'        { "[$($FullTimeStamp)] " + ('-' * 100) }
            'DoubleSeperation'  { "[$($FullTimeStamp)] " + ('=' * 100) }
            'ValidationSuccess' { "[$($FullTimeStamp)] [$($CallingFunction)]: The validation is successful. The process will now start." }
            'ValidationFail'    { "[$($FullTimeStamp)] [$($CallingFunction)]: The validation failed. The process will NOT start." }
            Default             { $InputMessage }
        }
        

        # Set the ForegroundColor
        [System.String]$ForegroundColor = switch ($MessageType) {
            'Busy'              { 'Yellow'  }
            'Success'           { 'Green'   }
            'Fail'              { 'Red'     }
            'Normal'            { 'White'   }
            'Special'           { 'Cyan'    }
            'SuccessNoAction'   { 'Green'   }
            'Seperation'        { 'White'   }
            'DoubleSeperation'  { 'White'   }
            'ValidationFail'    { 'White'   }
            Default             { 'DarkGray'}
        }

        # Set the BackgroundColor
        [System.String]$BackgroundColor = switch ($MessageType) {
            'ActionFail'        { 'DarkRed' }
            'ValidationFail'    { 'DarkRed' }
            Default             { ''        }
        }
    }
    
    process {
        # EXECUTION
        # Set the Write-Host parameters
        [System.Collections.Hashtable]$WriteHostParams = @{
            'Object'            = $FullMessage
            'ForegroundColor'   = $ForegroundColor
        }
        # Add BackgroundColor if specified
        if (-not [System.String]::IsNullOrEmpty($BackgroundColor)) {
            $WriteHostParams['BackgroundColor'] = $BackgroundColor
        }

        # Write the message
        Write-Host @WriteHostParams
    }
    
    end {
    }
}

### END OF FUNCTION
####################################################################################################
