#
# Module 'ModuleMainFunctionsCopy.psm1'
# Generated by  : Imraan Iotana
# Creation Date : January 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function copies and moves files and folders, showing the Windows Progressbar.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions or variables, that are in other files.
.EXAMPLE
    Copy-WithGUI -ThisFolder 'C:\Demo\CopyThisFolder' -IntoThisFolder 'D:\Archives'
.EXAMPLE
    Copy-WithGUI -ThisFolder 'C:\Demo\CopyThisFolder' -IntoThisFolder 'D:\Archives' -OpenFolder
.EXAMPLE
    Copy-WithGUI -ThisFolder 'C:\Demo\CopyThisFolder' -IntoThisFolder 'D:\Archives' -Overwrite -OpenFolder
.INPUTS
    [System.String]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : December 2025
    Last Update     : February 2026
.COPYRIGHT
    Copyright (C) Iotana. All rights reserved.
#>
####################################################################################################

function Copy-WithGUI {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The path of the source folder that will be copied.')]
        [System.String]$ThisFolder,

        [Parameter(Mandatory=$true,HelpMessage='The path of the folder into which the source folder will be copied.')]
        [System.String]$IntoThisFolder,

        [Parameter(Mandatory=$false,HelpMessage='Switch for overwriting an existing folder.')]
        [System.Management.Automation.SwitchParameter]$Overwrite,

        [Parameter(Mandatory=$false,HelpMessage='Switch for moving instead of copying.')]
        [System.Management.Automation.SwitchParameter]$Move,

        [Parameter(Mandatory=$false,HelpMessage='Switch for opening the destination folder.')]
        [System.Management.Automation.SwitchParameter]$OpenFolder
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Input
        [System.String]$FolderToCopy        = $ThisFolder
        [System.String]$FolderToCopyInto    = $IntoThisFolder

        ####################################################################################################
    }
    process {
        # VALIDATION
        # Validate the FolderToCopy
        if (-not(Test-Path -Path $FolderToCopy)) { Write-Line "The Source folder cannot be found. ($FolderToCopy)" -Type Fail ; Return }
        # Validate the FolderToCopyInto
        if (-not(Test-Path -Path $FolderToCopyInto)) { Write-Line "The Destinationfolder cannot be found. ($FolderToCopyInto)" -Type Fail ; Return }

        # GENERAL CONFIRMATION
        # Set the verb
        [System.String]$Verb = if ($Move.IsPresent) { 'MOVE' } else { 'COPY' }
        if ($Overwrite.IsPresent) { $Verb += ' (AND OVERWRITE)' }
        # Ask for confirmation to proceed
        if (-not(Get-UserConfirmation -Title "CONFIRM $Verb" -Body "This will $Verb the Folder:`n`n$FolderToCopy`n`ninto the Folder:`n`n$FolderToCopyInto`n`nAre you sure?")) { Return }


        # OVERWRITE CONFIRMATION
        # Set the Destination
        [System.String]$UltimateFolderPath = Join-Path -Path $FolderToCopyInto -ChildPath (Split-Path -Path $FolderToCopy -Leaf)
        # If the Destination already exists
        if (Test-Path -Path $UltimateFolderPath) {
            # Write the message
            Write-Line "The Destination already exists. ($UltimateFolderPath)" -Type Busy
            # Check if the folder should be overwritten
            [System.Boolean]$ShouldOverwrite = if ($Overwrite.IsPresent) {
                $true
            } else {
                Get-UserConfirmation -Title 'Confirm Overwrite' -Body "This will OVERWRITE the EXISTING Folder:`n`n$UltimateFolderPath`n`nAre you sure?"
            }
            # If the folder should not be overwritten, then exit
            if (-not $ShouldOverwrite) { Write-Line "The Destination has not be overwritten. ($UltimateFolderPath)" -Type Success ;  Return }
            # Remove the Destination
            Remove-WithGUI -Path $UltimateFolderPath -OutHost -Force
            # Write the message
            Write-Line "The existing Destination has been removed. ($UltimateFolderPath)" -Type Success
        }


        # PREPARATION
        # Create the Shell Object
        [System.__ComObject]$ShellObject        = New-Object -ComObject Shell.Application
        # Create and validate the Source Object
        [System.__ComObject]$SourceObject       = $ShellObject.Namespace($FolderToCopy)
        if (-not $SourceObject) { Write-Line "The Source folder is empty, or cannot be accessed. ($FolderToCopy)" -Type Fail ; Return }
        # Create and validate the Destination Object
        [System.__ComObject]$DestinationObject  = $ShellObject.Namespace($FolderToCopyInto)
        if (-not $DestinationObject) { Write-Line "The Destination folder cannot be accessed. ($FolderToCopyInto)" -Type Fail ; Return }


        # EXECUTION
        try {
            # Set the Action Verb
            [System.String]$ActionVerb = if ($Move.IsPresent) { 'Moving' } else { 'Copying' }
            # Set the Completion Verb
            [System.String]$CompletionVerb = if ($Move.IsPresent) { 'moved' } else { 'copied' }
            # Write the Action Message
            Write-Line "$ActionVerb the folder ($FolderToCopy) into the folder ($FolderToCopyInto)..." -Type Busy
            # Perform the Action
            if ($Move.IsPresent) {
                # Move the folder
                $DestinationObject.MoveHere($SourceObject,16)
            } else {
                # Copy the folder
                $DestinationObject.CopyHere($SourceObject,16)
            }
            # Write the Completion Message
            Write-Line "The folder has been $CompletionVerb. ($FolderToCopyInto)" -Type Success
            # Open the folder
            if ($OpenFolder) { Open-Folder -HighlightItem $UltimateFolderPath }
        }
        catch {
            Write-FullError
        }

    }
    end {
        # CLEANUP
        # Cleanup the Objects
        foreach ($VariableName in 'SourceObject','DestinationObject','ShellObject') {
            $VariableObject = Get-Variable -Name $VariableName -ValueOnly -ErrorAction SilentlyContinue
            if ($VariableObject) {
                [System.Runtime.InteropServices.Marshal]::ReleaseComObject($VariableObject) | Out-Null
                Remove-Variable -Name $VariableName -ErrorAction SilentlyContinue
            }
        }
    }


    ####################################################################################################
}

### END OF SCRIPT
####################################################################################################
