####################################################################################################
<#
.SYNOPSIS
    This function exports the details of shortcuts.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Export-ShortcutInformation -Path "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Acrobat Reader.lnk"
.EXAMPLE
    Export-ShortcutInformation -Path 'C:\Users\MyName\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessories'
.INPUTS
    [System.String]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.5.1
    Author          : Imraan Iotana
    Creation Date   : August 2025
    Last Update     : August 2025
#>
####################################################################################################

function Export-ShortcutInformation {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The StartMenu shortcut or folder, from which the information will be obtained.')]
        [System.String]
        $Path,

        [Parameter(Mandatory=$false,HelpMessage='The folder where the output will be placed.')]
        [Alias('OutputFolder')]
        [System.String]
        $ParentOutputFolder = (Get-Path -OutputFolder),

        [Parameter(Mandatory=$false,HelpMessage='Switch for opening the output folder.')]
        [System.Management.Automation.SwitchParameter]
        $OpenOutputFolder
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Function
        [System.String[]]$FunctionDetails       = @($MyInvocation.MyCommand,$PSCmdlet.ParameterSetName,$PSBoundParameters.GetEnumerator())
        # Start Menu Handlers
        [System.String]$SystemStartMenuFolder   = ('{0}\Microsoft\Windows\Start Menu\Programs' -f $ENV:PROGRAMDATA)
        [System.String]$UserStartMenuFolder     = ('{0}\Microsoft\Windows\Start Menu\Programs' -f $ENV:APPDATA)
        # Output Handlers
        [System.String[]]$PropertiesToWrite     = @('BaseName','TargetPath','WorkingDirectory','Arguments','StartMenuLocationShort','IconFilePath')
        [System.String]$AsteriskLine            = '******************************' # 25 asterisks
        [System.String]$Asterisk                = '*'
        [System.String]$BlankLine               = ''
        [System.String]$OutputHeaderPrefix      = '* Shortcut Properties - {0}'
        [System.String]$OutputFooter            = '* End of file'
        # Other Handlers
        [System.String]$ItemBaseName            = (Get-Item -Path $Path).BaseName

        ####################################################################################################
        ### SUPPORTING FUNCTIONS ###

        function Get-ActualOutputFolder {
            # Set the actual output folder
            [System.String]$OutputFolderName    = ('Shortcuts - {0}' -f $ItemBaseName)
            [System.String]$ActualOutputFolder  = Join-Path -Path $ParentOutputFolder -ChildPath $OutputFolderName
            # Return the result
            $ActualOutputFolder
        }

        function New-OutputFilePath {
            # Set the output file path
            [System.String]$OutputFileName      = ('_Shortcut Properties - {0}.txt' -f $ItemBaseName)
            [System.String]$ActualOutputFolder  = Get-ActualOutputFolder
            [System.String]$OutputFilePath      = Join-Path -Path $ActualOutputFolder -ChildPath $OutputFileName
            # Create the file
            New-Item -Path $OutputFilePath -ItemType File -Force | Out-Null
            # Return the result
            $OutputFilePath
        }

        function Write-ToOutputFile { param([System.String[]]$TextLines)
            # Write the TextLines to the OutputFile
            Add-Content -Path $OutputFilePath -Value $TextLines
        }

        function Write-ShortcutPropertiesOutputFile { param([PSCustomObject]$ShortcutPropertiesObject)
            # Write the object to the OutputFile
            Write-ToOutputFile $AsteriskLine,$ShortcutPropertiesObject.CounterTextLine,$AsteriskLine
            $ShortcutPropertiesObject.PropertiesToWrite | ForEach-Object { Write-ToOutputFile $ShortcutPropertiesObject.$_ }
            Write-ToOutputFile $AsteriskLine,$BlankLine
        }

        function Write-Header {
            # Write the Header
            Write-ToOutputFile $AsteriskLine,$Asterisk,($OutputHeaderPrefix -f $ItemBaseName),$Asterisk
            Write-ToOutputFile ('* Generated on: {0}' -f (Get-TimeStamp -Universal))
            Write-ToOutputFile ('* Generated by: {0}' -f $ENV:UserName)
            Write-ToOutputFile $Asterisk,$AsteriskLine,$BlankLine
        }

        function Write-Footer {
            # Write the Footer
            Write-ToOutputFile $AsteriskLine,$Asterisk,$OutputFooter,$Asterisk,$AsteriskLine
        }

        ####################################################################################################

        # Write the Begin message
        Write-Function -Begin $FunctionDetails
    }
    
    process {
        try {
            # If the item is a folder, then get all shortcuts in the folder
            [System.String[]]$ShortcutPathsArray = if (Test-Path -Path $Path -PathType Container) { (Get-ChildItem -Path $Path -Recurse -File).FullName } else { $Path }
            # If no items were found, then return
            if ($ShortcutPathsArray.Count -eq 0) { Write-Host ('No shortcuts were found in the folder: ({0})' -f $Path) ; Return }
            # Set the output file path
            [System.String]$OutputFilePath = New-OutputFilePath
            # Write the Header
            Write-Header
            # For each shortcut in the array
            foreach ($ShortcutPath in $ShortcutPathsArray) {
                # Write the message
                Write-Line ('Getting the properties of the shortcut: ({0})' -f $ShortcutPath)
                # Create a ShortcutPropertiesObject
                [System.__ComObject]$ShortcutPropertiesObject = New-ShortcutPropertiesObject -Path $ShortcutPath
                # Create a hashtable for the additional properties
                [System.Collections.Hashtable]$AdditionalProperties = @{
                    CounterTextLine         = ('* Shortcut {0} of {1}' -f ($ShortcutPathsArray.IndexOf($ShortcutPath) + 1),$ShortcutPathsArray.Count)
                }
                # Add the additional properties to the object
                $AdditionalProperties.GetEnumerator() | ForEach-Object { Add-Member -InputObject $ShortcutPropertiesObject -NotePropertyName $_.Name -NotePropertyValue $_.Value }
                # Write the shortcut properties to the OutputFile
                Write-ShortcutPropertiesOutputFile $ShortcutPropertiesObject
                # Create the image files
                Export-ShortcutImage -InputObject $ShortcutPropertiesObject -OutputFolder (Get-ActualOutputFolder) -PNG
                Export-ShortcutImage -InputObject $ShortcutPropertiesObject -OutputFolder (Get-ActualOutputFolder) -ICO
            }
            # Write the Footer
            Write-Footer
        }
        catch {
            Write-FullError
        }
    }
    
    end {
        # Open the output folder
        if ($OpenOutputFolder) { Open-Folder -Path (Get-ActualOutputFolder) }
        # Write the End message
        Write-Function -End $FunctionDetails
    }
}

### END OF SCRIPT
####################################################################################################
