#
# Module manifest for module 'ModuleSettings.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 29-1-2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the Application Settings Module.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-ModuleApplicationSettings
.INPUTS
    [System.Windows.Forms.TabControl]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-ModuleApplicationSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The Parent TabControl to which this new TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl = $Global:MainTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Tab properties
        [System.String]$TabTitle        = 'Settings'
        [System.String]$ModuleVersion   = '5.7.1'

        # Handlers
        [System.Boolean]$IsSCCMServer   = $Global:ApplicationObject.IsSCCMServer

        ####################################################################################################
    }
    
    process {
        try {
            # Write the message
            Write-Line "Importing Module $TabTitle $ModuleVersion"

            # Create the Module TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage -Parent $ParentTabControl -Title $TabTitle

            # Create a SubTabControl
            [System.Windows.Forms.TabControl]$ParentSubTabControl = Invoke-SubTabControl -ParentTabPage $ParentTabPage

            # Load the SCCM/MECM SubModule only on an SCCM server
            if ($IsSCCMServer) { Import-SubModuleSCCMSettings -ParentTabControl $ParentSubTabControl }

            # Import the other SubModules
            Import-SubModuleGeneralSettings -ParentTabControl $ParentSubTabControl
            Import-SubModuleMaintenance -ParentTabControl $ParentSubTabControl
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################

