#
# Module manifest for module 'ModuleSettings.psm1'
# Generated by  : Imraan Iotana
# Generated on  : 29-1-2026
# Last Update   : January 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the Application Settings Module.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-ModuleApplicationSettings
.INPUTS
    [System.Windows.Forms.TabControl]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : January 2026
#>
####################################################################################################
# MAKE PSM1 
function Import-ModuleApplicationSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The Parent TabControl to which this new TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl = $Global:MainTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Tab properties
        [System.String]$TabTitle        = 'Settings'
        [System.String]$ModuleVersion   = '5.7.0'

        # Handlers
        [System.Boolean]$IsSCCMServer = $Global:ApplicationObject.IsSCCMServer

        ####################################################################################################
    }
    
    process {
        try {
            # Write the message
            Write-Line "Importing Module $TabTitle $ModuleVersion"
            # Create the Module TabPage
            [System.Windows.Forms.TabPage]$Global:ApplicationSettingsTabPage = New-TabPage -Parent $ParentTabControl -Title $TabTitle
            # Create a SubTabControl
            [System.Windows.Forms.TabControl]$Global:ModuleApplicationSettingsTabControl = Invoke-SubTabControl -ParentTabPage $Global:ApplicationSettingsTabPage
            # Load the SCCM/MECM module only on an SCCM server
            if ($IsSCCMServer) { Import-SubModuleSCCMSettings -ParentTabControl $Global:ModuleApplicationSettingsTabControl }
            # Import the SubModules
            Import-SubModuleGeneralSettings -ParentTabControl $Global:ModuleApplicationSettingsTabControl
            if (-Not($IsSCCMServer)) { Import-SubModuleAppLockerSettings -ParentTabControl $Global:ModuleApplicationSettingsTabControl }
            Import-SubModuleMaintenance -ParentTabControl $Global:ModuleApplicationSettingsTabControl
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################
