#
# Module manifest for module 'SubModuleGeneralSettings.psm1'
# Generated by  : Imraan Iotana
# Creation Date : January 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the General Settings SubModule.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-SubModuleFolderSettings
.INPUTS
    This function has no input parameters.
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-SubModuleGeneralSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The TabControl to which this Module TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Submodule properties
        [System.Collections.Hashtable]$SubModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = [System.String]'General Settings'
            Version             = [System.String]'5.7.1'
            BackGroundColor     = [System.String]'Cornsilk'
        }

        ####################################################################################################
    }
    
    process {
        try {
            # Create the SubModule TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @SubModuleProperties

            # Import the Features
            Import-FeatureFolderSettings -ParentTabPage $ParentTabPage
            Import-FeaturePersonalSettings -ParentTabPage $ParentTabPage
            Import-FeatureHelp -ParentTabPage $ParentTabPage
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function imports the Feature Folder Settings.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-FeatureFolderSettings -ParentTabPage $MyGlobalTabPage
.INPUTS
    [PSCustomObject]
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.0.0282
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-FeatureFolderSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The ApplicationObject containing the Settings.')]
        [PSCustomObject]$ApplicationObject = $Global:ApplicationObject,

        [Parameter(Mandatory=$true,HelpMessage='The Parent object to which this feature will be added.')]
        [System.Windows.Forms.TabPage]$ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = [System.String]'Folder Settings'
            Color           = [System.String]'Brown'
            NumberOfRows    = [System.Int32]4
        }

        # Set the Default Values for the TextBoxes
        [System.String]$DefaultDSLFolder        = $ApplicationObject.Settings.DefaultDSLFolder

        # Set the Button Properties Array
        [System.Object[][]]$FolderButtonsArray  = @( (1,'Browse') , (2,'Open') , (3,'Copy') , (4,'Paste') , (5,'Default') )

        ####################################################################################################
        ### TEXTBOX PROPERTIES ###

        # Set the Output Folder TextBox Properties
        [System.Collections.Hashtable]$OutputFolderTextBoxProperties = @{
            RowNumber               = 1
            Label                   = 'My Output Folder:'
            ToolTip                 = 'Enter the path to your output folder. You can use the "Copy" and "Paste" buttons to easily copy and paste the path. The "Default" button will reset the path to the default value.'
            PropertyName            = 'MSet_SGen_FFol_OutputFolderTextBox'
            SizeType                = 'Large'
            DefaultValue            = $ApplicationObject.DefaultOutputFolder
            ButtonPropertiesArray   = $FolderButtonsArray
        }

        ####################################################################################################
    } 
    
    process {
        # Create the GroupBox (This groupbox must be global to relate to groupboxes in other features)
        [System.Windows.Forms.GroupBox]$Global:MSet_SGen_FFol_GroupBox = $ParentGroupBox = Invoke-Groupbox @GroupBoxProperties -OnSubTab
       
        # Create the Output Folder TextBox
        [System.Windows.Forms.TextBox]$Global:MSet_SGen_FFol_OutputFolderTextBox = Invoke-TextBox @OutputFolderTextBoxProperties -ParentGroupBox $ParentGroupBox

        # Create the ASFSDSLFolderTextBox
        [System.Windows.Forms.TextBox]$Global:ASFSDSLFolderTextBox = Invoke-TextBox -ParentGroupBox $ParentGroupBox -RowNumber 3 -SizeType Large -Type Input -Label 'Software Library (DSL):' -PropertyName 'ASFSDSLFolderTextBox' -DefaultValue $DefaultDSLFolder -ButtonPropertiesArray $FolderButtonsArray
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function imports the Feature Personal Settings.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Import-FeaturePersonalSettings -ParentTabPage $MyParentTabPage
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-FeaturePersonalSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]$ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = [System.String]'Personal Settings'
            Color           = [System.String]'Brown'
            NumberOfRows    = [System.Int32]4
            GroupBoxAbove   = [System.Windows.Forms.GroupBox]$Global:MSet_SGen_FFol_GroupBox
        }
        
        # Set the Button Properties Array
        [System.Object[][]]$ButtonPropertiesArray = @( (1,'Copy') , (2,'Paste') , (5,'Clear') )

        ####################################################################################################
    } 
    
    process {
        try {
            # Create the GroupBox (This groupbox must be global to relate to groupboxes in other features)
            [System.Windows.Forms.GroupBox]$Global:MSet_SGen_FPer_GroupBox = $ParentGroupBox = Invoke-Groupbox @GroupBoxProperties -OnSubTab

            # Create the ASPSUserFullNameTextBox
            [System.Windows.Forms.TextBox]$Global:ASPSUserFullNameTextBox = Invoke-TextBox -ParentGroupBox $ParentGroupBox -RowNumber 1 -SizeType Large -Type Input -Label 'My Full Name:' -PropertyName 'ASPSUserFullNameTextBox' -ButtonPropertiesArray $ButtonPropertiesArray

            # Create the ASPSUserEmailTextBox
            [System.Windows.Forms.TextBox]$Global:ASPSUserEmailTextBox = Invoke-TextBox -ParentGroupBox $ParentGroupBox -RowNumber 3 -SizeType Large -Type Input -Label 'My Email Address:' -PropertyName 'ASPSUserEmailTextBox' -ButtonPropertiesArray $ButtonPropertiesArray
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


