#
# Module 'SubModuleHelp.psm1'
# Generated by  : Imraan Iotana
# Creation Date : January 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the Help SubModule.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-SubModuleHelp
.INPUTS
    This function has no input parameters.
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-SubModuleHelp {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The TabControl to which this Module TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Submodule properties
        [System.Collections.Hashtable]$SubModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = [System.String]'Help'
            Version             = [System.String]'5.7.1'
            BackGroundColor     = [System.String]'Cornsilk'
        }

        # Set the Helpfile properties
        #[System.String]$HelpFileName    = "HelpFile SubModule $($SubModuleProperties.Title).pdf"
        #[System.String]$HelpFilePath    = (Get-ChildItem -Path $PSScriptRoot -File -Recurse -Filter $HelpFileName -ErrorAction SilentlyContinue).FullName


        ####################################################################################################
    }
    
    process {
        try {
            # Create the SubModule TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @SubModuleProperties

            <# Register the help file in the main Help menu
            if ($HelpFilePath) {
                Register-HelpMenuItem -Text "SubModule $($SubModuleProperties.Title) Help" -HelpFilePath $HelpFilePath
            } else {
                Write-Line "Help file not found for submodule '$($SubModuleProperties.Title)'. Expected at: $HelpFilePath" -Type Fail
            }#>

            # Import the Features
            Import-FeatureHelp -ParentTabPage $ParentTabPage
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function imports the feature Help.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-FeatureHelp -ParentTabPage $MyParentTabPage
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-FeatureHelp {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]
        $ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = 'Help'
            Color           = 'Brown'
            NumberOfRows    = 4
        }

        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the Help Buttons
        [System.Collections.Hashtable[]]$ButtonPropertiesArray = @(
            @{
                ColumnNumber    = 1
                Text            = 'Create Desktop Shortcut'
                ToolTip         = 'Create a Desktop Shortcut.'
                SizeType        = 'Large'
                Image           = 'Desktop.png'
                Function        = { Invoke-NewShortcut -Desktop }
            }
            @{
                ColumnNumber    = 2
                Text            = 'Create StartMenu Shortcut'
                ToolTip         = 'Create a StartMenu Shortcut.'
                SizeType        = 'Large'
                Image           = 'Menu.png'
                Function        = { Invoke-NewShortcut }
            }
            @{
                ColumnNumber    = 3
                Text            = 'Open Logfolder'
                ToolTip         = 'Open the Logfolder in File Explorer.'
                SizeType        = 'Large'
                Image           = 'folder_page.png'
                Function        = { Open-Folder -Path (Get-ApplicationSetting -Name 'LogFolder') }
            }
            @{
                ColumnNumber    = 4
                Text            = 'Version History'
                ToolTip         = 'Open the Version History in Notepad.'
                SizeType        = 'Large'
                Image           = 'file_extension_log.png'
                Function        = { Open-VersionHistoryFile }
            }
            @{
                ColumnNumber    = 5
                Text            = 'Reset All Settings'
                ToolTip         = 'Reset all settings to their default values.'
                SizeType        = 'Large'
                Image           = 'arrow_rotate_clockwise.png'
                Function        = { Invoke-RegistrySettings -ResetAll }
            }
        )

        # Set the Help Buttons 2
        [System.Collections.Hashtable[]]$ButtonPropertiesArray2 = @(
            @{
                ColumnNumber    = 5
                Text            = 'Application Settings Key'
                SizeType        = 'Large'
                DefaultIcon     = 'Registry'
                Function        = { Start-RegistryEditor -ApplicationSettingsKey }
            }
        )
    } 
    
    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$Global:MSet_SHel_GroupBox = $ParentGroupBox = Invoke-Groupbox @GroupBoxProperties -OnSubTab

        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $ButtonPropertiesArray -ParentGroupBox $ParentGroupBox -RowNumber 1
        Invoke-ButtonLine -ButtonPropertiesArray $ButtonPropertiesArray2 -ParentGroupBox $ParentGroupBox -RowNumber 3
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function opens the Version History file in Notepad.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Open-VersionHistoryFile
.INPUTS
    None
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : February 2026
    Last Update     : February 2026
#>
####################################################################################################

function Open-VersionHistoryFile {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The ApplicationObject containing the Settings.')]
        [PSCustomObject]$ApplicationObject = $Global:ApplicationObject
    )

    begin {
    }

    process {
        try {
            Start-Process -FilePath notepad -ArgumentList $ApplicationObject.VersionHistoryFilePath
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function creates a new Shortcut for the Packaging Assistant.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Invoke-NewShortcut -Desktop
.INPUTS
    [PSCustomObject]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : March 2025
    Last Update     : February 2026
#>
####################################################################################################

function Invoke-NewShortcut {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The ApplicationObject containing the Settings.')]
        [PSCustomObject]$ApplicationObject = $Global:ApplicationObject,

        [Parameter(Mandatory=$false,HelpMessage='Switch for creating a Desktop shortcut.')]
        [System.Management.Automation.SwitchParameter]$Desktop
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

            # Set the Shortcut Properties Object
            [System.Collections.Hashtable]$ShortcutPropertiesObject = @{
                ApplicationName = $ApplicationObject.Name
                PowershellPath  = $ApplicationObject.PowerShellExecutablePath
                IconSourcePath  = (Get-ApplicationSetting -Name MainApplicationIcon)
            }

        ####################################################################################################
    }
    
    process {
        try {
            # PROPERTIES
            # Add the Destination Folder
            $ShortcutPropertiesObject['DestinationFolder']      = if ($Desktop.IsPresent) { $ApplicationObject.UserDesktopFolder } else { $ApplicationObject.UserStartMenuFolder }
            # Add the Shortcut File Name
            $ShortcutPropertiesObject['ShortcutFileName']       = "$($ShortcutPropertiesObject.ApplicationName).lnk"
            # Add the Shortcut Full Path
            $ShortcutPropertiesObject['ShortcutFullPath']       = Join-Path -Path $ShortcutPropertiesObject.DestinationFolder -ChildPath $ShortcutPropertiesObject.ShortcutFileName
            # Add the Icon Destination Folder
            $ShortcutPropertiesObject['IconDestinationFolder']  = Join-Path -Path $ENV:APPDATA -ChildPath $ShortcutPropertiesObject.ApplicationName
            # Add the Icon File Name
            $ShortcutPropertiesObject['IconFileName']           = (Get-Item -Path $ShortcutPropertiesObject.IconSourcePath).Name
            # Add the Local Icon Path
            $ShortcutPropertiesObject['LocalIconPath']          = Join-Path -Path $ShortcutPropertiesObject.IconDestinationFolder -ChildPath $ShortcutPropertiesObject.IconFileName
            # Add the PS1 File Path
            $ShortcutPropertiesObject['PS1FilePath']            = (Join-Path -Path $ApplicationObject.RootFolder -ChildPath $ApplicationObject.MainScriptFileName)
            # Add the Shortcut Argument
            $ShortcutPropertiesObject['ShortcutArgument']       = ('-Executionpolicy Bypass -WindowStyle Normal -File "{0}"' -f $ShortcutPropertiesObject.PS1FilePath)

            # Create the Shortcut
            New-Shortcut -ShortcutPropertiesObject $ShortcutPropertiesObject
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function creates a new Shortcut based on the provided properties.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    New-Shortcut -ShortcutPropertiesObject $ShortcutPropertiesObject
.INPUTS
    [System.Collections.Hashtable]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : February 2026
    Last Update     : February 2026
#>
####################################################################################################

function New-Shortcut {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='Hashtable containing the Shortcut properties.')]
        [System.Collections.Hashtable]$ShortcutPropertiesObject
    )

    begin {
    }

    process {
        try {
            # CONFIRMATION
            # Get the ShortcutFullPath
            [System.String]$ShortcutFullPath = $ShortcutPropertiesObject.ShortcutFullPath
            # Get user confirmation
            if (-Not(Get-UserConfirmation -Title 'Create New Shortcut' -Body "This will create the following Shortcut:`n`n$ShortcutFullPath`n`nAre you sure?" )) { Return }


            # ICON
            # Get the IconDestinationFolder
            [System.String]$IconDestinationFolder = $ShortcutPropertiesObject.IconDestinationFolder
            # Create the Icon Destination Folder if it doesn't exist
            if (-Not (Test-Path -Path $IconDestinationFolder)) {
                New-Item -Path $IconDestinationFolder -ItemType Directory -Force
            }
            # Copy the Icon to the Destination Folder
            Copy-Item -Path $ShortcutPropertiesObject.IconSourcePath -Destination $IconDestinationFolder -Force


            # SHORTCUT CREATION
            # Create the Shortcut
            Write-Line "Creating the Shortcut ($ShortcutFullPath)..."
            # Create a new WScript Shortcut object
            [System.__ComObject]$WScriptShellObject     = New-Object -ComObject WScript.Shell
            [System.__ComObject]$WScriptShortcutObject  = $WScriptShellObject.CreateShortcut($ShortcutFullPath)
            $WScriptShortcutObject.TargetPath           = $ShortcutPropertiesObject.PowershellPath
            $WScriptShortcutObject.Arguments            = $ShortcutPropertiesObject.ShortcutArgument
            $WScriptShortcutObject.IconLocation         = $ShortcutPropertiesObject.LocalIconPath
            # Save the new object
            $WScriptShortcutObject.Save()
            # Write the message
            Write-Line "Succesfully created the Shortcut ($ShortcutFullPath)..."
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


