#
# Module 'SubModuleGeneralSettings.psm1'
# Generated by  : Imraan Iotana
# Creation Date : January 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the General Settings SubModule.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-SubModuleGeneralSettings
.INPUTS
    This function has no input parameters.
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : See below at 'Main Properties'
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-SubModuleGeneralSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The TabControl to which this Module TabPage will be added.')]
        [System.Windows.Forms.TabControl]$ParentTabControl
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Submodule properties
        [System.Collections.Hashtable]$SubModuleProperties = @{
            ParentTabControl    = $ParentTabControl
            Title               = [System.String]'General Settings'
            Version             = [System.String]'5.7.1'
            BackGroundColor     = [System.String]'Cornsilk'
        }

        # Set the Helpfile properties
        [System.String]$HelpFileName    = "HelpFile SubModule $($SubModuleProperties.Title).pdf"
        [System.String]$HelpFilePath    = (Get-ChildItem -Path $PSScriptRoot -File -Recurse -Filter $HelpFileName -ErrorAction SilentlyContinue).FullName


        ####################################################################################################
    }
    
    process {
        try {
            # Create the SubModule TabPage
            [System.Windows.Forms.TabPage]$ParentTabPage = New-TabPage @SubModuleProperties

            # Register the help file in the main Help menu
            if ($HelpFilePath) {
                Register-HelpMenuItem -Text "SubModule $($SubModuleProperties.Title) Help" -HelpFilePath $HelpFilePath
            } else {
                Write-Line "Help file not found for submodule '$($SubModuleProperties.Title)'. Expected at: $HelpFilePath" -Type Fail
            }

            # Import the Features
            Import-FeatureFolderSettings -ParentTabPage $ParentTabPage
            Import-FeaturePersonalSettings -ParentTabPage $ParentTabPage
            #Import-FeatureHelp -ParentTabPage $ParentTabPage
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function imports the Feature Folder Settings.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-FeatureFolderSettings -ParentTabPage $MyGlobalTabPage
.INPUTS
    [PSCustomObject]
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-FeatureFolderSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The ApplicationObject containing the Settings.')]
        [PSCustomObject]$ApplicationObject = $Global:ApplicationObject,

        [Parameter(Mandatory=$true,HelpMessage='The Parent object to which this feature will be added.')]
        [System.Windows.Forms.TabPage]$ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = [System.String]'Folder Settings'
            Color           = [System.String]'Brown'
            NumberOfRows    = [System.Int32]4
        }

        # Set the Button Properties Array
        [System.Object[][]]$FolderButtonsArray  = @( (1,'Browse') , (2,'Open') , (3,'Copy') , (4,'Paste') , (5,'Default') )

        ####################################################################################################
        ### TEXTBOX PROPERTIES ###

        # Set the Output Folder TextBox Properties
        [System.Collections.Hashtable]$OutputFolderTextBoxProperties = @{
            RowNumber               = 1
            Label                   = 'My Output Folder:'
            ToolTip                 = 'Enter the path to your output folder. You can use the "Copy" and "Paste" buttons to easily copy and paste the path. The "Default" button will reset the path to the default value.'
            PropertyName            = 'MSet_SGen_FFol_OutputFolderTextBox'
            SizeType                = 'Large'
            DefaultValue            = $ApplicationObject.DefaultOutputFolder
            ButtonPropertiesArray   = $FolderButtonsArray
        }

        # Set the DSL Folder TextBox Properties
        [System.Collections.Hashtable]$DSLFolderTextBoxProperties = @{
            RowNumber               = 3
            Label                   = 'Software Library (DSL):'
            ToolTip                 = 'Enter the path to your Software Library (DSL) folder. You can use the "Copy" and "Paste" buttons to easily copy and paste the path. The "Default" button will reset the path to the default value.'
            PropertyName            = 'MSet_SGen_FFol_DSLFolderTextBox'
            SizeType                = 'Large'
            DefaultValue            = $ApplicationObject.Settings.DefaultDSLFolder
            ButtonPropertiesArray   = $FolderButtonsArray
        }

        ####################################################################################################
    } 
    
    process {
        # Create the GroupBox (This groupbox must be global to relate to groupboxes in other features)
        [System.Windows.Forms.GroupBox]$Global:MSet_SGen_FFol_GroupBox = $ParentGroupBox = Invoke-Groupbox @GroupBoxProperties -OnSubTab
       
        # Create the Output Folder TextBox
        [System.Windows.Forms.TextBox]$Global:MSet_SGen_FFol_OutputFolderTextBox = Invoke-TextBox @OutputFolderTextBoxProperties -ParentGroupBox $ParentGroupBox

        # Create the DSL Folder TextBox
        [System.Windows.Forms.TextBox]$Global:MSet_SGen_FFol_DSLFolderTextBox = Invoke-TextBox @DSLFolderTextBoxProperties -ParentGroupBox $ParentGroupBox
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function imports the Feature Personal Settings.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-FeaturePersonalSettings -ParentTabPage $MyParentTabPage
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-FeaturePersonalSettings {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]$ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = [System.String]'Personal Settings'
            Color           = [System.String]'Brown'
            NumberOfRows    = [System.Int32]4
            GroupBoxAbove   = [System.Windows.Forms.GroupBox]$Global:MSet_SGen_FFol_GroupBox
        }
        
        # Set the Button Properties Array
        [System.Object[][]]$ButtonPropertiesArray = @( (1,'Copy') , (2,'Paste') , (5,'Clear') )

        ####################################################################################################
        ### TEXTBOX PROPERTIES ###

        # Set the User Full Name TextBox Properties
        [System.Collections.Hashtable]$UserFullNameTextBoxProperties = @{
            RowNumber               = 1
            Label                   = 'My Full Name:'
            ToolTip                 = 'Enter your full name. This is used for documentation purposes and to pre-fill the name field in several reports.'
            PropertyName            = 'MSet_SGen_FPer_UserFullNameTextBox'
            SizeType                = 'Large'
            ButtonPropertiesArray   = $ButtonPropertiesArray
        }

        # Set the User Email TextBox Properties
        [System.Collections.Hashtable]$UserEmailTextBoxProperties = @{
            RowNumber               = 3
            Label                   = 'My Email Address:'
            ToolTip                 = 'Enter your email address. This is used for documentation purposes and to pre-fill the email field in several reports.'
            PropertyName            = 'MSet_SGen_FPer_UserEmailTextBox'
            SizeType                = 'Large'
            ButtonPropertiesArray   = $ButtonPropertiesArray
        }

        ####################################################################################################
    } 
    
    process {
        try {
            # Create the GroupBox (This groupbox must be global to relate to groupboxes in other features)
            [System.Windows.Forms.GroupBox]$Global:MSet_SGen_FPer_GroupBox = $ParentGroupBox = Invoke-Groupbox @GroupBoxProperties -OnSubTab

            # Create the User Full Name TextBox
            [System.Windows.Forms.TextBox]$Global:MSet_SGen_FPer_UserFullNameTextBox = Invoke-TextBox @UserFullNameTextBoxProperties -ParentGroupBox $ParentGroupBox

            # Create the User Email TextBox
            [System.Windows.Forms.TextBox]$Global:MSet_SGen_FPer_UserEmailTextBox = Invoke-TextBox @UserEmailTextBoxProperties -ParentGroupBox $ParentGroupBox
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


