#
# Module manifest for module 'SubModuleGeneralSettingFeatureHelp.psm1'
# Generated by  : Imraan Iotana
# Creation Date : January 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the feature Help.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-FeatureHelp -ParentTabPage $MyParentTabPage
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-FeatureHelp {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]
        $ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = 'Help'
            Color           = 'Brown'
            NumberOfRows    = 1
            GroupBoxAbove   = $Global:MSet_SGen_FPer_GroupBox
        }

        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the GetHelpButtons
        [System.Collections.Hashtable[]]$ButtonPropertiesArray = @(
            @{
                ColumnNumber    = 1
                Text            = 'Desktop Shortcut'
                ToolTip         = 'Create a Desktop Shortcut.'
                Image           = 'Desktop.png'
                Function        = { Invoke-NewShortcut -Desktop }
            }
            @{
                ColumnNumber    = 2
                Text            = 'StartMenu Shortcut'
                ToolTip         = 'Create a StartMenu Shortcut.'
                Image           = 'Menu.png'
                Function        = { Invoke-NewShortcut -StartMenu }
            }
            @{
                ColumnNumber    = 3
                Text            = 'Open Logfolder'
                ToolTip         = 'Open the Logfolder in File Explorer.'
                Image           = 'folder_page.png'
                Function        = { Open-Folder -Path (Get-ApplicationSetting -Name 'LogFolder') }
            }
            @{
                ColumnNumber    = 4
                Text            = 'Reset All'
                ToolTip         = 'Reset all settings to their default values.'
                Image           = 'arrow_rotate_clockwise.png'
                Function        = { Invoke-RegistrySettings -ResetAll }
            }
            @{
                ColumnNumber    = 5
                Text            = 'Version History'
                ToolTip         = 'Open the Version History in Notepad.'
                Function        = { Start-Process -FilePath notepad -ArgumentList $Global:ApplicationObject.VersionHistoryFilePath }
            }
        )
    } 
    
    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$ParentGroupBox = Invoke-Groupbox @GroupBoxProperties -OnSubTab

        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $ButtonPropertiesArray -ParentGroupBox $ParentGroupBox -RowNumber 1
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function creates a new Shortcut for the Packaging Assistant.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Invoke-NewShortcut -Desktop
.INPUTS
    [PSCustomObject]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : March 2025
    Last Update     : February 2026
#>
####################################################################################################

function Invoke-NewShortcut {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The ApplicationObject containing the Settings.')]
        [PSCustomObject]$ApplicationObject = $Global:ApplicationObject,

        [Parameter(Mandatory=$true,ParameterSetName='CreateDesktopShortcut',HelpMessage='Switch for creating a Desktop shortcut.')]
        [System.Management.Automation.SwitchParameter]$Desktop,

        [Parameter(Mandatory=$true,ParameterSetName='CreateStartMenuShortcut',HelpMessage='Switch for creating a StartMenu shortcut.')]
        [System.Management.Automation.SwitchParameter]$StartMenu
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # Function
        [System.String]$ParameterSetName    = $PSCmdlet.ParameterSetName

        # User Folder Handlers
        [System.String]$UserDesktopFolder   = $ApplicationObject.UserDesktopFolder
        [System.String]$UserStartMenuFolder = $ApplicationObject.UserStartMenuFolder

        # Shortcut Handlers
        [System.String]$ApplicationName      = $ApplicationObject.Name
        [System.String]$PowershellPath      = (Join-Path -Path $ApplicationObject.WindowsFolder -ChildPath 'System32\WindowsPowerShell\v1.0\powershell.exe')
        [System.String]$ShortcutFileName    = "$ApplicationName.lnk"
        [System.String]$IconSourcePath      = (Get-ApplicationSetting -Name MainApplicationIcon)

        # Argument Handlers
        [System.String]$PS1FilePath         = (Join-Path -Path $ApplicationObject.RootFolder -ChildPath 'PackagingAssistant.ps1')
        [System.String]$ShortcutArgument    = ('-Executionpolicy Bypass -WindowStyle Normal -File "{0}"' -f $PS1FilePath)

        ####################################################################################################
    }
    
    process {
        try {
            # PROPERTIES
            # Set the Destination Path based on the ParameterSetName
            [System.String]$DestinationFolder = switch ($ParameterSetName) {
                'CreateDesktopShortcut'     { $UserDesktopFolder }
                'CreateStartMenuShortcut'   { $UserStartMenuFolder }
            }
            # Set the Shortcut Full Path
            [System.String]$ShortcutFullPath = Join-Path -Path $DestinationFolder -ChildPath $ShortcutFileName

            # CONFIRMATION
            # Get user confirmation
            if (-Not(Get-UserConfirmation -Title 'Create New Shortcut' -Body "This will create the following Shortcut.`n`n$ShortcutFullPath`n`nAre you sure?" )) { Return }

            # ICON
            # Set the Icon Destination Folder
            [System.String]$IconDestinationFolder = Join-Path -Path $ENV:APPDATA -ChildPath $ApplicationName
            # Copy the Icon to the Destination Folder
            New-Item -Path $IconDestinationFolder -ItemType Directory -Force
            Copy-Item -Path $IconSourcePath -Destination $IconDestinationFolder -Force
            # Get the Local Icon Path
            [System.String]$IconFileName    = (Get-Item -Path $IconSourcePath).Name 
            [System.String]$LocalIconPath   = (Get-ChildItem -Path $IconDestinationFolder -File | Where-Object { $_.Name -eq $IconFileName }).FullName

            # SHORTCUT CREATION
            # Create the Shortcut
            Write-Line "Creating the Shortcut ($ShortcutFullPath)..."
            # Create a new WScript Shortcut object
            [System.__ComObject]$WScriptShellObject     = New-Object -ComObject WScript.Shell
            [System.__ComObject]$WScriptShortcutObject  = $WScriptShellObject.CreateShortcut($ShortcutFullPath)
            $WScriptShortcutObject.TargetPath           = $PowershellPath
            $WScriptShortcutObject.Arguments            = $ShortcutArgument
            $WScriptShortcutObject.IconLocation         = $LocalIconPath
            # Save the new object
            $WScriptShortcutObject.Save()
            # Write the message
            Write-Line "Succesfully created the Shortcut ($ShortcutFullPath)..."
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


