#
# Module manifest for module 'SubModuleGeneralSettingFeatureHelp.psm1'
# Generated by  : Imraan Iotana
# Creation Date : January 2026
# Last Update   : February 2026
#

####################################################################################################
<#
.SYNOPSIS
    This function imports the feature Help.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains functions and variables that are in other files.
.EXAMPLE
    Import-FeatureHelp -ParentTabPage $MyParentTabPage
.INPUTS
    [System.Windows.Forms.TabPage]
.OUTPUTS
    This function returns no stream-output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : October 2023
    Last Update     : February 2026
#>
####################################################################################################

function Import-FeatureHelp {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true,HelpMessage='The Parent TabPage to which this Feature will be added.')]
        [System.Windows.Forms.TabPage]
        $ParentTabPage
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

        # GroupBox properties
        [System.Collections.Hashtable]$GroupBoxProperties = @{
            ParentTabPage   = $ParentTabPage
            Title           = 'Help'
            Color           = 'Brown'
            NumberOfRows    = 1
            GroupBoxAbove   = $Global:MSet_SGen_FPer_GroupBox
        }

        ####################################################################################################
        ### BUTTON PROPERTIES ###

        # Set the GetHelpButtons
        [System.Collections.Hashtable[]]$ButtonPropertiesArray = @(
            @{
                ColumnNumber    = 1
                Text            = 'Desktop Shortcut'
                ToolTip         = 'Create a Desktop Shortcut.'
                Image           = 'Desktop.png'
                Function        = { Invoke-NewShortcut -Desktop }
            }
            @{
                ColumnNumber    = 2
                Text            = 'StartMenu Shortcut'
                ToolTip         = 'Create a StartMenu Shortcut.'
                Image           = 'Menu.png'
                Function        = { Invoke-NewShortcut }
            }
            @{
                ColumnNumber    = 3
                Text            = 'Open Logfolder'
                ToolTip         = 'Open the Logfolder in File Explorer.'
                Image           = 'folder_page.png'
                Function        = { Open-Folder -Path (Get-ApplicationSetting -Name 'LogFolder') }
            }
            @{
                ColumnNumber    = 4
                Text            = 'Reset All'
                ToolTip         = 'Reset all settings to their default values.'
                Image           = 'arrow_rotate_clockwise.png'
                Function        = { Invoke-RegistrySettings -ResetAll }
            }
            @{
                ColumnNumber    = 5
                Text            = 'Version History'
                ToolTip         = 'Open the Version History in Notepad.'
                Function        = { Start-Process -FilePath notepad -ArgumentList $Global:ApplicationObject.VersionHistoryFilePath }
            }
        )
    } 
    
    process {
        # Create the GroupBox
        [System.Windows.Forms.GroupBox]$ParentGroupBox = Invoke-Groupbox @GroupBoxProperties -OnSubTab

        # Create the Buttons
        Invoke-ButtonLine -ButtonPropertiesArray $ButtonPropertiesArray -ParentGroupBox $ParentGroupBox -RowNumber 1
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


####################################################################################################
<#
.SYNOPSIS
    This function creates a new Shortcut for the Packaging Assistant.
.DESCRIPTION
    This function is part of the Packaging Assistant. It contains references to functions and variables that are in other files.
.EXAMPLE
    Invoke-NewShortcut -Desktop
.INPUTS
    [PSCustomObject]
    [System.Management.Automation.SwitchParameter]
.OUTPUTS
    This function returns no stream output.
.NOTES
    Version         : 5.7.1
    Author          : Imraan Iotana
    Creation Date   : March 2025
    Last Update     : February 2026
#>
####################################################################################################

function Invoke-NewShortcut {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false,HelpMessage='The ApplicationObject containing the Settings.')]
        [PSCustomObject]$ApplicationObject = $Global:ApplicationObject,

        [Parameter(Mandatory=$true,HelpMessage='Switch for creating a Desktop shortcut.')]
        [System.Management.Automation.SwitchParameter]$Desktop
    )

    begin {
        ####################################################################################################
        ### MAIN PROPERTIES ###

            # Set the Shortcut Properties Object
            [System.Collections.Hashtable]$ShortcutPropertiesObject = @{
                ApplicationName = $ApplicationObject.Name
                PowershellPath  = $ApplicationObject.PowerShellExecutablePath
                IconSourcePath  = (Get-ApplicationSetting -Name MainApplicationIcon)
            }

        ####################################################################################################
    }
    
    process {
        try {
            # PROPERTIES
            # Add the Destination Folder to the Object
            $ShortcutPropertiesObject['DestinationFolder']      = if ($Desktop.IsPresent) { $ApplicationObject.UserDesktopFolder } else { $ApplicationObject.UserStartMenuFolder }
            # Add the Shortcut File Name to the Object
            $ShortcutPropertiesObject['ShortcutFileName']       = "$($ShortcutPropertiesObject.ApplicationName).lnk"
            # Add the Shortcut Full Path to the Object
            $ShortcutPropertiesObject['ShortcutFullPath']       = Join-Path -Path $ShortcutPropertiesObject.DestinationFolder -ChildPath $ShortcutPropertiesObject.ShortcutFileName
            # Add the Icon Destination Folder to the Object
            $ShortcutPropertiesObject['IconDestinationFolder']  = Join-Path -Path $ENV:APPDATA -ChildPath $ShortcutPropertiesObject.ApplicationName
            # Add the Icon File name to the Object
            $ShortcutPropertiesObject['IconFileName']           = (Get-Item -Path $ShortcutPropertiesObject.IconSourcePath).Name
            # Add the Local Icon Path to the Object
            $ShortcutPropertiesObject['LocalIconPath']          = Join-Path -Path $ShortcutPropertiesObject.IconDestinationFolder -ChildPath $ShortcutPropertiesObject.IconFileName
            # Add the PS1 File Path to the Object
            $ShortcutPropertiesObject['PS1FilePath']            = (Join-Path -Path $ApplicationObject.RootFolder -ChildPath $ApplicationObject.MainScriptFileName)
            # Add the Shortcut Argument to the Object
            $ShortcutPropertiesObject['ShortcutArgument']       = ('-Executionpolicy Bypass -WindowStyle Normal -File "{0}"' -f $ShortcutPropertiesObject.PS1FilePath)


            # CONFIRMATION
            # Get the ShortcutFullPath
            [System.String]$ShortcutFullPath = $ShortcutPropertiesObject.ShortcutFullPath
            # Get user confirmation
            if (-Not(Get-UserConfirmation -Title 'Create New Shortcut' -Body "This will create the following Shortcut:`n`n$ShortcutFullPath`n`nAre you sure?" )) { Return }


            # ICON
            # Get the IconDestinationFolder
            [System.String]$IconDestinationFolder = $ShortcutPropertiesObject.IconDestinationFolder
            # Create the Icon Destination Folder if it doesn't exist
            if (-Not (Test-Path -Path $IconDestinationFolder)) {
                New-Item -Path $IconDestinationFolder -ItemType Directory -Force
            }
            # Copy the Icon to the Destination Folder
            Copy-Item -Path $ShortcutPropertiesObject.IconSourcePath -Destination $IconDestinationFolder -Force


            # SHORTCUT CREATION
            # Create the Shortcut
            Write-Line "Creating the Shortcut ($ShortcutFullPath)..."
            # Create a new WScript Shortcut object
            [System.__ComObject]$WScriptShellObject     = New-Object -ComObject WScript.Shell
            [System.__ComObject]$WScriptShortcutObject  = $WScriptShellObject.CreateShortcut($ShortcutFullPath)
            $WScriptShortcutObject.TargetPath           = $ShortcutPropertiesObject.PowershellPath
            $WScriptShortcutObject.Arguments            = $ShortcutPropertiesObject.ShortcutArgument
            $WScriptShortcutObject.IconLocation         = $ShortcutPropertiesObject.LocalIconPath
            # Save the new object
            $WScriptShortcutObject.Save()
            # Write the message
            Write-Line "Succesfully created the Shortcut ($ShortcutFullPath)..."
        }
        catch {
            Write-FullError
        }
    }

    end {
    }
}

### END OF SCRIPT
####################################################################################################


